$(function(){
		$(".title li").click(function(){
//            var $this=$(this);
//            alert($this.index());
			$(this).addClass("active").siblings().removeClass("active");
			$("#content .mod").eq($(".title li").index(this)).show().siblings("#content .mod").hide();
		});
	});
	
$(function(){
	var project =[
	{
		"id": 2,
		"pid": 0,
		"name": "ETS Demo project",
		"type": null,
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 19116,
		"automation": 2891,
		"manaul": 16225,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99778,
		"pid": 2,
		"name": "A Suite 3",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 1,
		"automation": 1,
		"manaul": 0,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 44549,
		"pid": 2,
		"name": "OSCE Test Cases",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 18284,
		"automation": 2697,
		"manaul": 15587,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99556,
		"pid": 2,
		"name": "BoBo",
		"type": "7",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 1,
		"automation": 0,
		"manaul": 1,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 90616,
		"pid": 2,
		"name": "UI  Automation Operation Suite",
		"type": "7",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 17,
		"automation": 0,
		"manaul": 17,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99531,
		"pid": -2,
		"name": "A Suite 2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 73,
		"automation": 14,
		"manaul": 59,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 79373,
		"pid": -2,
		"name": "Operation Suite(No Delete)",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 44,
		"automation": 36,
		"manaul": 8,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99775,
		"pid": -2,
		"name": "YxTest2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 696,
		"automation": 143,
		"manaul": 553,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 79373,
		"pid": -2,
		"name": "Operation Suite(No Delete)",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 44,
		"automation": 36,
		"manaul": 8,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99775,
		"pid": -2,
		"name": "YxTest2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 696,
		"automation": 143,
		"manaul": 553,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 79373,
		"pid": -2,
		"name": "Operation Suite(No Delete)",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 44,
		"automation": 36,
		"manaul": 8,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99775,
		"pid": -2,
		"name": "YxTest2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 696,
		"automation": 143,
		"manaul": 553,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 79373,
		"pid": -2,
		"name": "Operation Suite(No Delete)",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 44,
		"automation": 36,
		"manaul": 8,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99775,
		"pid": -2,
		"name": "YxTest2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 696,
		"automation": 143,
		"manaul": 553,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 79373,
		"pid": -2,
		"name": "Operation Suite(No Delete)",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 44,
		"automation": 36,
		"manaul": 8,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99775,
		"pid": -2,
		"name": "YxTest2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 696,
		"automation": 143,
		"manaul": 553,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 79373,
		"pid": -2,
		"name": "Operation Suite(No Delete)",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 44,
		"automation": 36,
		"manaul": 8,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99775,
		"pid": -2,
		"name": "YxTest2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 696,
		"automation": 143,
		"manaul": 553,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 79373,
		"pid": -2,
		"name": "Operation Suite(No Delete)",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 44,
		"automation": 36,
		"manaul": 8,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99775,
		"pid": -2,
		"name": "YxTest2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 696,
		"automation": 143,
		"manaul": 553,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 79373,
		"pid": -2,
		"name": "Operation Suite(No Delete)",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 44,
		"automation": 36,
		"manaul": 8,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99775,
		"pid": -2,
		"name": "YxTest2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 696,
		"automation": 143,
		"manaul": 553,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 79373,
		"pid": -2,
		"name": "Operation Suite(No Delete)",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 44,
		"automation": 36,
		"manaul": 8,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99775,
		"pid": -2,
		"name": "YxTest2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 696,
		"automation": 143,
		"manaul": 553,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 79373,
		"pid": -2,
		"name": "Operation Suite(No Delete)",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 44,
		"automation": 36,
		"manaul": 8,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99775,
		"pid": -2,
		"name": "YxTest2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 696,
		"automation": 143,
		"manaul": 553,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 79373,
		"pid": -2,
		"name": "Operation Suite(No Delete)",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 44,
		"automation": 36,
		"manaul": 8,
		"parentName": null,
		"custom_field": null
	},
	{
		"id": 99775,
		"pid": -2,
		"name": "YxTest2",
		"type": "3",
		"realid": null,
		"isCompleted": null,
		"suiteid": null,
		"isParent": null,
		"num": 696,
		"automation": 143,
		"manaul": 553,
		"parentName": null,
		"custom_field": null
	}
];
	
	$(document).ready(function() {
		var s = "";
		for(var i = 0; i < project.length; i++) {
			s = "<tr><td>" + project[i].id  + "</td><td>" +
				project[i].name + "</td><td>" + project[i].num + "</td><td>" +project[i].automation + "</td><td>" +
				project[i].manaul +"</td><td>"+"<button onclick=alert('删除成功！') >delete</button>"+"</td></tr>";
			$("#table").append(s);
		}
	});
})
